apiVersion: v1
kind: Secret
metadata:
  name: agent-fastapi-secrets
type: Opaque
stringData:
  OPENAI_API_KEY: ""
  ZEP_API_KEY: ""
  LANGFUSE_PUBLIC_KEY: ""
  LANGFUSE_SECRET_KEY: ""
  LANGFUSE_HOST: ""
